# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Computer Networks I
author: Cleto Martín
exclude_patterns:
  - README.md
  - .venv

execute:
  execute_notebooks: off

sphinx:
  config:
    language: en
    html_show_copyright: false
  extra_extensions:
    - sphinx-prompt
