name: test-book

on: pull_request

# This job installs dependencies and builds the book
jobs:
  test-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Build the book
      - name: Build the book
        run: |
          make pre-commit
          make
